name: repository_search
description: Test task for the vacancy Flutter Developer

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # DI
  get_it: ^7.6.4
  injectable: ^2.3.2

  # Network
  dio: ^5.1.2
  json_annotation: ^4.8.1

  # Bloc
  flutter_bloc: ^8.1.3

  # Localization
  easy_localization: ^3.0.1

  # Utils
  freezed_annotation: ^2.2.0
  dartz: ^0.10.1
  flutter_spinkit: ^5.2.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # DI
  injectable_generator: ^2.4.1

  # Network
  json_serializable: ^6.7.0

  # Utils
  build_runner: ^2.3.3
  freezed: ^2.3.4

  # Code style
  flutter_lints: ^2.0.0
  dart_code_metrics: ^5.6.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
